### ISSUE TITLE
Directory git

### ISSUE THREAD

**Issue by michieldewilde** [RealTeamSWAG/swagsite#4]
Bij andere projecten wordt alleen de plugin zijn folder op version control gezet. Geen miserie met composer dan.

**Comment by michieldewilde** [comment]
Should still happen

**Comment by pietercolpaert** [comment]
Still probably... @StanCallewaert can you take care of this? Would love to be able to have someone work further on the code next year ;)

**Comment by pietercolpaert** [comment]
@StanCallewaert Take care of this. Top priority.

**Comment by Dobbelsteen** [comment]
Late comment, but done a while ago, got rid of ~280k lines of code
